DATA_FOLDER: "../../../data/"  # Change this to the path of the data folder

DATASET: 21


PLOTS_SAVE_FOLDER: "plots/"
RESULTS_FOLDER: "results/" 
X_OFFSET: 0.13673 
DISTANCE_PER_TIC: 0.0022

MAP_GRID_METERS: 30.0
MAP_X_MIN: -15.0
MAP_Y_MIN: -15.0
MAP_X_MAX: 30.0
MAP_Y_MAX: 30.0
MAP_RES: 0.05

# SIGMOID_THRESHOLD: 0.5
N_PARTICLES: 100
SIGMA_V: 0.1
SIGMA_W: 0.01
BOT_LOCAL_FRAME_HEIGHT: 0.14700999999999997 
FLOOR_Z_RANGE: 0.1

